In [1]:
import numpy as np
from import_data import load_data
x_train, y_train, x_test, y_test = load_data()

CSV loaded
Data loaded


In [34]:
from sklearn.metrics import accuracy_score, fbeta_score

import tensorflow as tf
import tensorflow.contrib.keras as k
from tensorflow.contrib.keras.python.keras.models import Sequential
from tensorflow.contrib.keras.python.keras.layers import Dense, Dropout, Flatten
from tensorflow.contrib.keras.python.keras.layers import Conv2D, MaxPooling2D

model = Sequential()
model.add(Conv2D(32, kernel_size=(3),
             activation='relu',
             input_shape=(48, 48, 1)))

model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.5))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(7, activation='softmax'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(x_train, y_train,
      batch_size=128,
      epochs=1,
      verbose=1,
      validation_data=(x_test, y_test))

from os.path import expanduser
model.save(expanduser("softmodel0to1.hd5"))

Train on 28709 samples, validate on 3589 samples
Epoch 1/1
28709/28709 [==============================] - 502s - loss: 0.3633 - acc: 0.8620 - val_loss: 0.3216 - val_acc: 0.8743


In [2]:
from os.path import expanduser
from tensorflow.contrib.keras.python.keras.models import load_model
from import_data import process_output
from train import test_model

model = load_model(expanduser("~/emotion/model.hd5"))
accuracy, fbeta = test_model(model, x_test, y_test)
print("Accuracy: %s" % accuracy)
print("F-Beta: %s" % fbeta)

ValueError: Can't handle mix of multilabel-indicator and continuous-multioutput

In [19]:
predictions = make_prediction(predictions)
print(predictions)

[0, 6, 3, 5, 6, 4, 4, 4, 0, 4, 5, 3, 6, 6, 4, 6, 5, 5, 5, 5, 6, 4, 6, 6, 6, 4, 5, 6, 6, 3, 6, 4, 4, 6, 0, 6, 5, 2, 3, 6, 0, 6, 4, 4, 6, 6, 3, 6, 6, 6, 4, 5, 6, 3, 0, 6, 5, 6, 6, 4, 4, 6, 4, 6, 4, 0, 3, 6, 6, 4, 4, 3, 6, 6, 6, 6, 6, 5, 6, 4, 6, 6, 6, 4, 6, 6, 2, 0, 6, 5, 6, 4, 0, 6, 4, 6, 4, 5, 4, 6, 6, 6, 6, 6, 3, 6, 6, 6, 5, 6, 6, 0, 4, 5, 3, 6, 6, 4, 6, 6, 6, 3, 5, 6, 4, 4, 4, 6, 6, 6, 6, 6, 4, 4, 6, 6, 4, 3, 4, 0, 5, 0, 6, 4, 0, 6, 5, 3, 6, 6, 6, 6, 6, 6, 4, 4, 6, 6, 6, 3, 4, 4, 3, 5, 6, 6, 6, 6, 3, 6, 5, 5, 6, 5, 6, 5, 4, 6, 5, 6, 4, 6, 6, 6, 0, 6, 5, 5, 6, 6, 3, 6, 6, 4, 3, 6, 5, 6, 6, 4, 6, 0, 4, 2, 6, 6, 4, 6, 4, 4, 6, 6, 5, 4, 4, 6, 4, 4, 4, 4, 3, 5, 5, 5, 4, 4, 5, 6, 6, 4, 3, 6, 6, 6, 6, 6, 0, 4, 6, 6, 4, 4, 0, 4, 6, 4, 4, 4, 3, 6, 6, 6, 4, 4, 4, 6, 6, 3, 3, 6, 6, 0, 4, 6, 4, 4, 6, 6, 6, 6, 6, 6, 4, 4, 4, 4, 4, 6, 0, 6, 0, 4, 3, 6, 6, 6, 6, 5, 4, 4, 4, 4, 6, 6, 4, 4, 5, 6, 4, 6, 6, 0, 5, 0, 4, 4, 4, 4, 6, 4, 6, 6, 4, 6, 6, 6, 6, 6, 4, 6, 6, 6, 6, 0, 6, 0, 4, 6, 5, 6, 3, 6, 6, 

ValueError: Can't handle mix of multilabel-indicator and multiclass

In [20]:
from import_data import process_output
predictions = process_output(predictions)

In [21]:
predictions

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [22]:
print("Accuracy: %s" % accuracy_score(y_test, predictions))
print(fbeta_score(y_test, np.array(predictions) > 0.2, beta=2, average='samples'))

Accuracy: 0.311228754528
0.311228754528


In [28]:
from train import test_model
#model = load_data(expanduser("~/emotion/model.h5"))

accuracy, fbeta = test_model(model, x_test, y_test)
print("Accuracy: %s" % accuracy)
print("F-Beta: %s" % fbeta)

TypeError: test_model() takes 2 positional arguments but 3 were given

In [47]:
def test_model(model, x_test, y_test):
    predictions = model.predict(x_test, batch_size=128)
    index_predictions = []
    for row in predictions:
        max_index = 0
        max_value = row[0]
        for index, value in enumerate(row):
            if value > max_value:
                max_index = index
        index_predictions.append(max_index)
    final_predictions = process_output(index_predictions)
    accuracy = accuracy_score(y_test, final_predictions)
    fbeta = fbeta_score(y_test, np.array(final_predictions) > 0.2, beta=2, average='samples')
    return accuracy, fbeta

In [48]:
accuracy, fbeta = test_model(model, x_train, y_train)
print("Accuracy: %s" % accuracy)
print("F-Beta: %s" % fbeta)

Accuracy: 0.240551743356
F-Beta: 0.240551743356


In [44]:
predictions = model.predict(x_test, batch_size=128)
index_predictions = []
for row in predictions:
    max_index = 0
    max_value = row[0]
    for index, value in enumerate(row):
        if value > max_value:
            max_index = index
    index_predictions.append(max_index)
final_predictions = process_output(index_predictions)

[ 0.19775678  0.01599375  0.12535514  0.15254663  0.16253935  0.05017528
  0.23774447]
[ 0.13942088  0.01534347  0.09589794  0.18963067  0.27599072  0.02971552
  0.22128241]
[ 0.08286595  0.00503293  0.21117599  0.18083283  0.16052161  0.06070327
  0.08705125]
[ 0.07542466  0.01319412  0.09510279  0.11259545  0.12183733  0.13718136
  0.10045666]
[ 0.13808747  0.01606243  0.14586522  0.07773422  0.31515381  0.02709937
  0.18898499]
[ 0.19106981  0.01132473  0.21463723  0.0885046   0.19479358  0.14377536
  0.10363218]
[ 0.17313288  0.01040699  0.13746481  0.13556443  0.29119498  0.0289225
  0.19583835]
[ 0.07243594  0.00414225  0.0406423   0.74882782  0.05311485  0.0030676
  0.0638709 ]
[ 0.10955606  0.01256176  0.25321814  0.13511373  0.1204957   0.20275533
  0.11717691]
[ 0.14351358  0.00987771  0.13701455  0.34809428  0.19687808  0.0313373
  0.08973194]


In [41]:
predictions

array([[ 0.19775678,  0.01599375,  0.12535514, ...,  0.16253935,
         0.05017528,  0.23774447],
       [ 0.13942088,  0.01534347,  0.09589794, ...,  0.27599072,
         0.02971552,  0.22128241],
       [ 0.08286595,  0.00503293,  0.21117599, ...,  0.16052161,
         0.06070327,  0.08705125],
       ..., 
       [ 0.05237806,  0.01019659,  0.07280996, ...,  0.16076474,
         0.05498865,  0.19568123],
       [ 0.19393939,  0.01158739,  0.13539676, ...,  0.28887644,
         0.05343383,  0.17328572],
       [ 0.06644735,  0.00993373,  0.15354712, ...,  0.13058978,
         0.02967988,  0.17463171]], dtype=float32)

In [42]:
index_predictions

[6,
 6,
 6,
 6,
 6,
 4,
 6,
 3,
 6,
 4,
 6,
 3,
 6,
 6,
 4,
 6,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 4,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 5,
 6,
 5,
 6,
 3,
 6,
 6,
 6,
 4,
 4,
 6,
 6,
 3,
 6,
 6,
 6,
 6,
 5,
 6,
 6,
 0,
 6,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 4,
 6,
 6,
 6,
 4,
 4,
 6,
 6,
 6,
 6,
 6,
 6,
 5,
 6,
 4,
 6,
 6,
 6,
 4,
 6,
 6,
 4,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 5,
 6,
 6,
 6,
 6,
 6,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 2,
 6,
 5,
 4,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 4,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 4,
 6,
 6,
 6,
 4,
 6,
 4,
 4,
 6,
 0,
 6,
 4,
 6,
 6,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 4,
 6,
 6,
 6,
 3,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 3,
 6,
 6,
 5,
 6,
 5,
 6,
 6,
 4,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 4,
 6,
 5,
 6,
 6,
 6,
 4,
 3,
 6,
 5,
 6,
 6,
 0,
 6,
 4,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 4,
 6,
 5,
 6,
 6,
 4,
 4,
 5,
 6,
 6,
 6,
 3,
 6,
 6,
 6,
 6,
 6,
 6,
 4,
 6,
 6,
 6,
 6,
 0,
 6,
 6,
 6,
 6,
 4,
 4,
 6,


In [43]:
final_predictions

array([[ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [46]:
accuracy = accuracy_score(y_test, final_predictions)
fbeta = fbeta_score(y_test, np.array(final_predictions) > 0.2, beta=2, average='samples')
print("Accuracy: %s" % accuracy)
print("F-Beta: %s" % fbeta)

Accuracy: 0.2454722764
F-Beta: 0.2454722764


In [3]:
model = load_model(expanduser("~/emotion/model.hd5"))
model.evaluate(x_test, y_test, batch_size=128, verbose=1)
#print("Accuracy: %s" % accuracy)
#print("F-Beta: %s" % fbeta)

3589/3589 [==============================] - 29s    


[0.32979841217685124, 0.87151224452428211]

In [6]:
from import_data import process_images, process_output
import pandas as pd
data = pd.read_csv("fer2013.csv")
validation_set = data.loc[data['Usage'] == "PublicTest"]

x_validate = process_images(validation_set["pixels"])
y_validate = process_output(validation_set["emotion"])
model.evaluate(x_validate, y_validate, batch_size=128, verbose=1)

3584/3589 [============================>.] - ETA: 0s

[0.3272267019443108, 0.87258695953235743]

In [7]:
print(model.metrics_names)

['loss', 'acc']


In [39]:
predictions = model.predict(x_test, batch_size=128)
predictions

array([[ 0.2583147 ,  0.04087767,  0.17710347, ...,  0.16430633,
         0.08239405,  0.18856739],
       [ 0.19169424,  0.04595682,  0.13225666, ...,  0.23552869,
         0.06623318,  0.15513612],
       [ 0.11494466,  0.02356886,  0.24118586, ...,  0.1780571 ,
         0.11533236,  0.13640265],
       ..., 
       [ 0.05745805,  0.01416327,  0.1017886 , ...,  0.14026503,
         0.12957968,  0.25354853],
       [ 0.24079879,  0.03113532,  0.11887378, ...,  0.22839639,
         0.07385628,  0.1507092 ],
       [ 0.12742852,  0.02527102,  0.22075914, ...,  0.20383018,
         0.06784619,  0.24233304]], dtype=float32)

In [10]:
model.save("softmodel.h5")

In [40]:
index_predictions = []
for row in predictions:
    max_index = 0
    max_value = row[0]
    for index, value in enumerate(row):
        if value > max_value:
            max_index = index
    index_predictions.append(max_index)
final_predictions = process_output(index_predictions)

In [33]:
final_predictions

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [13]:
final_predictions - y_test

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0., -1.,  1.],
       [ 0.,  0.,  0., ...,  1.,  0., -1.],
       ..., 
       [-1.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0., -1., ...,  0.,  0.,  1.]])

In [20]:
difference = np.sum((final_predictions * final_predictions) * (final_predictions - y_test))
difference

2485.0

In [21]:
from math import sqrt
sqrt(difference)

49.84977432245807

In [22]:
from sklearn.metrics import accuracy_score
accuracy_score(final_predictions, y_test)

0.30760657564781274

In [23]:
final_predictions

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [24]:
y_test

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       ..., 
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.]])

In [41]:
good = 0
bad = 0
for pred, test in zip(final_predictions, y_test):
    if np.all(pred == test):
        good = good + 1
    else:
        bad = bad + 1
print("Accuracy: %s" % (good / (good + bad)))
print("%s correct, %s incorrect" % (good, bad))

Accuracy: 0.2713847868487044
974 correct, 2615 incorrect
